### ISSUE TITLE
io functions do not work

### ISSUE THREAD

**Issue by Woovie** [Freeeaky/GTALua#1]
Attempt a simple script to write to a file, at C:\ or just filename. Neither open the file using io.open.

Example script: http://privatepaste.com/55c0480eec

**Comment by Freeeaky** [comment]
They actually work, you used the io API wrong.

```
local fOutput = io.open(outputFile,"w")
    if fOutput then
        fOutput:write("{\r\n")
        for i=1,#vehicleList do
            local hashKey = natives.GAMEPLAY.GET_HASH_KEY(vehicleList[i])
            fOutput:write("    "..vehicleList[i].." = "..hashKey..",\r\n")
        end
        fOutput:write("}")
        fOutput:flush()
        fOutput:close()
        print("done")
    else
        print("error in opening file")
    end
```

(Note: `outputFile = "hashNameTable.txt"`)

io.open returns a file handle.
You were using the default io functions, which writes to the standard output file (=> that doesn't exist). Take a look here: http://lua-users.org/wiki/IoLibraryTutorial

With the fixed up code I generated a hashNameTable.txt :)
