### ISSUE TITLE
Missing GET stats wrapper for out param

### ISSUE THREAD

**Issue by gir489** [Freeeaky/GTALua#10]
STAT_GET_INT(Hash statHash, int *valuePointer, int p2) // 0x1C6FE43E
STAT_GET_FLOAT(Hash statHash, float *valuePointer, Any p2) // 0xFCBDA612
STAT_GET_BOOL(Hash statHash, int *valuePointer, Any p2) // 0x28A3DD2B

These are still handled incorrectly.

**Comment by Freeeaky** [comment]
This has already been adressed and is already fixed for the new version.
Am 01.05.2015 00:39 schrieb "gir489" <notifications@github.com>:
