### ISSUE TITLE
REMOVE_PED_ELEGANTLY

### ISSUE THREAD

**Issue by gcWorld** [Freeeaky/GTALua#15]
Calling the native PED.REMOVE_PED_ELEGANTLY leads to an exception in GTALua.dll

```
[20:35:25] CORE: An exception occurred while executing 'GTALua.dll'
```

See gist for example script
https://gist.github.com/gcWorld/ab11c6b53ba31dec5613

Might be related to #13

**Comment by Freeeaky** [comment]
My guess would be that it also takes a pointer as parameter, I will check in alter.
Thanks for the report.

**Comment by Freeeaky** [comment]
This is related to https://github.com/Freeeaky/GTALua/issues/13
As many delete/remove functions, REMOVE_PED_ELEGANTLY also takes a pointer - This will be fixed for the new version as it has a new class called CMemoryBlock
