### ISSUE TITLE
GET_CURRENT_PED_WEAPON causes game to crash

### ISSUE THREAD

**Issue by kmcgurty** [Freeeaky/GTALua#22]
Using `natives.WEAPON.GET_CURRENT_PED_WEAPON(plyPed, 0, false)` will make the game crash. From what I understand, that's how you're supposed to use it. Changing 0 to any weapon hash and changing false to true still causes a crash

**Comment by Freeeaky** [comment]
The second parameter is an OUT-parameter, which means that it takes a pointer. However, GTALua 1.0.1 doesn't support them yet. The upcoming version (1.1.0) will.

**Comment by kmcgurty** [comment]
Sweet, thanks. Do you have an ETA yet?

**Comment by Freeeaky** [comment]
Sadly, not an exact one. Everything is running smoothly, but the documentation is a lot of work and will take some time. I also have an important exam tomorrow, so I'm guessing by tomorrow or saturday.

Thanks for taking the time to report.
