### ISSUE TITLE
GET_CURRENT_PED_WEAPON and GET_MAX_AMMO pointers

### ISSUE THREAD

**Issue by SNikvand** [Freeeaky/GTALua#27]
The following functions require pointers. Changes in native_call_layout.ini

GET_CURRENT_PED_WEAPON=aib)b -> GET_CURRENT_PED_WEAPON=amb)b
Refer to the following:
Any GET_CURRENT_PED_WEAPON(Ped ped, Hash *weapHash, BOOL p2) // 0xB0237302

GET_MAX_AMMO=aai)b -> GET_MAX_AMMO=aam)b
Refer to the following: 
Any GET_MAX_AMMO(Ped ped, Hash WeapHash, int *ammo) // 0x0B294796

**Comment by Freeeaky** [comment]
Updated! Thanks for the report.
