### ISSUE TITLE
More keys for Keycodes.lua

### ISSUE THREAD

**Issue by SNikvand** [Freeeaky/GTALua#29]
VK_OEM_1 = 186 -- OEM_1 (: ;)
VK_OEM_2 = 191 -- OEM_2 (? /)
VK_OEM_3 = 192 -- OEM_3 (~ `)
VK_OEM_4 = 219 -- OEM_4 ({ [)
VK_OEM_5 = 220 -- OEM_5 (| )
VK_OEM_6 = 221 -- OEM_6 (} ])
VK_OEM_7 = 222 -- OEM_7 (" ')
VK_OEM_PERIOD = 190 -- OEM_PERIOD (> .)
VK_OEM_PLUS = 187 -- OEM_PLUS (+ =)
VK_OEM_MINUS = 189 -- OEM_MINUS (_ -)

**Comment by Freeeaky** [comment]
Thanks! Good job.
