### ISSUE TITLE
"no such operator defined" CsScriptThread.lua:70

### ISSUE THREAD

**Issue by jacobgc** [Freeeaky/GTALua#32]
Hey, when I try to print data sent to a function from a menu button I get the "no such operator defined" and I did some research on it but it was all about C++ and or luabind.

Here is the function;
function sinhax:menuChanger(newmenu)
        print(newmenu) -- debug as newmenu:Open() gives a nill value
        newmenu:Open()
end

and here is the button;
mainmenu:AddOption("Player", "menuChanger", "playermenu")

Thanks for any support :)

**Comment by jacobgc** [comment]
EDIT: you use luabind.dll so i'm wondering if its not my mistake...

**Comment by Freeeaky** [comment]
Thank you for the report, I'll fix this soon.

**Comment by Freeeaky** [comment]
Fixed :)
