### ISSUE TITLE
Console opens on a non-existent monitor

### ISSUE THREAD

**Issue by kmcgurty** [Freeeaky/GTALua#36]
With having 2 monitors and when the main is on the right and secondary on the left, the console tries to open on the outside of the right monitor (beyond the existing monitor)

Edit: If you're having this problem, a work around is to open it in your task bar and push win+left arrow

**Comment by Freeeaky** [comment]
Thanks for the report!

**Comment by Freeeaky** [comment]
This is kind of fixed now, there is a gtalua.ini - you can turn off automatic positioning and set a manual position for the console. I might add a "proper" fix for this later.
