### ISSUE TITLE
Request - Custom controls for GUI

### ISSUE THREAD

**Issue by jacobgc** [Freeeaky/GTALua#37]
Hey, The title pretty much says it all. Custom controls would be nice for the GUI module! E.G. Up, down, left, right and back

**Comment by Freeeaky** [comment]
Okay, i'll add customizability for the next version. For now it's called
"SimpleMenu" for a reason ;)
Thank you for the suggestion.
Am 10.05.2015 13:15 schrieb "Jacob Gee-Clarke" notifications@github.com:

**Comment by jacobgc** [comment]
:) Do you have an idea on when the next update will be?

**Comment by Freeeaky** [comment]
Pretty soon, but not before thursday - I want to find as much bugs as
possible before it, I don't like doing daily updates. However, if I commit
any changes to the menu you can just update the lua files.
Am 10.05.2015 14:43 schrieb "Jacob Gee-Clarke" notifications@github.com:

**Comment by jacobgc** [comment]
ah ok, its just with that bug. It means I need to rethink how to make a multiple menu system D:

**Comment by Freeeaky** [comment]
As for multiple menus I'll add support for automatic submenus and stuff. I
should probabbly rename it to AdvancedMenu :)
Am 10.05.2015 14:47 schrieb "Jacob Gee-Clarke" notifications@github.com:

**Comment by jacobgc** [comment]
:D I guess ill just wait until you add that :P

**Comment by kmcgurty** [comment]
If you don't want to wait you can use my GUI lib https://mega.co.nz/#!Z9VlkD4R!rnYVJ3dvm_6bgC9WoWq7QmUd0foluBxVrIxuQ-b8t9o

**Comment by jacobgc** [comment]
Ok. Ill try and figure out how to use this :P

**Comment by jacobgc** [comment]
nvm. just read that its an addon :P

**Comment by Freeeaky** [comment]
This has been added, thanks for the suggestion. For reference, take a look at example 3.
