### ISSUE TITLE
file.FindFiles not working

### ISSUE THREAD

**Issue by alexandre-leites** [Freeeaky/GTALua#38]
I've created a test addon which runs the following function:

```
function TestAddon:LoadAddons()
    local success, dir_list, _file_list = file.FindFiles("GTALua/addons/*")

    -- Failure to load addons
    if not success then
        print("Failed to get directory list for GTALua/addons/TestAddon/addons")
        print("Unable to load addons!")
        return false
    end

    -- addon Loading
    print("")
    for _,addon_name in pairs(dir_list) do
        -- Do not load addons that start with "_"
        if addon_name:sub(1,1) == "_" then
            print("Ignored addon ", addon_name)
        else
            print("Loading addon ", addon_name, "...")
            self:LoadAddon(addon_name)
        end
    end
    print("")

    return true
end
```

It is almost the same code as the _main() function runs, however it seems to not work on addons. I've tried some other combinations such as '_', '/_', '../../*', etc.

**Comment by alexandre-leites** [comment]
Maybe it is related to the same problem when trying

```
include("subdir/"..name.."/file.lua")
```

to load a file.lua inside of a subdir of my addon.

**Comment by alexandre-leites** [comment]
```
local success,dir_list,_ = file.FindFiles("GTALua/addons/*")
```

Works outside of a class or method, but not inside. Same for includes. Probably you'll need to set path somewhere in the lua bind.

**Comment by Freeeaky** [comment]
This will not be fixed. Be sure to do file operations like that outside of the thread. For GTALua 1.1.2 these functions will be blocked within threads.

But thanks a lot for taking the time to report this :)
