### ISSUE TITLE
Update For Two Natives

### ISSUE THREAD

**Issue by SirGoodsmoke** [Freeeaky/GTALua#40]
(natives.ini)

_0x2AA720E4287BF269=0x2AA720E4287BF269
_0x8E0A582209A62695=0x8E0A582209A62695

TO:

SET_VEHICLE_NEON_LIGHTS_ON=0x2AA720E4287BF269
SET_VEHICLE_NEON_LIGHTS_COLOUR=0x8E0A582209A62695

---

 (natives_call_layout.ini)

_0x2AA720E4287BF269=aab)v
_0x8E0A582209A62695=aaaa)v

TO:

SET_VEHICLE_NEON_LIGHTS_ON=aab)v
SET_VEHICLE_NEON_LIGHTS_COLOUR=aiii)v

**Comment by Freeeaky** [comment]
Thank you, will be in the next version.

**Comment by Freeeaky** [comment]
Added, thanks again :)
