### ISSUE TITLE
I want to ask something:  How can I close the console window?

### ISSUE THREAD

**Issue by wijat** [Freeeaky/GTALua#41]
I'm a Chinese developer. And English is not very good,So I just can ask question in here..

I use GTALua to make GTA5 mod now.  It is simple and convenient. I'm very happy to use it.

Now, I have a question, how to close the console window in Lua?

![image](https://cloud.githubusercontent.com/assets/8220843/7627548/155fe704-fa4b-11e4-9675-d0b704d26ba8.png)

This thing....
How close It????

**Comment by Freeeaky** [comment]
As of now, this is not possible.
The next version however will have a config file where you can disable the console.

**Comment by wijat** [comment]
I got it......

**Comment by wijat** [comment]
I have a suggest..

If I want to get the Player aiming position, Can I just use a function to call like this: 

LocalPlayer():GetAimingPosition()

**Comment by Freeeaky** [comment]
There is LocalPlayer():GetAimingEntity() if you want to know who you're looking at.

**Comment by wijat** [comment]
Not that

I mean:
I want to create some entity on the aiming position , I just want to get the aiming position. 
I don't care aiming thing.

**Comment by Freeeaky** [comment]
Ah okay.
Thanks for the suggestion.

You can use the CAM natives for that (for now).
