### ISSUE TITLE
I can not build the asi file

### ISSUE THREAD

**Issue by wijat** [Freeeaky/GTALua#44]
I download the source project,but I can not build it........
![qq 20150519013907](https://cloud.githubusercontent.com/assets/8220843/7686394/18219ef8-fdc8-11e4-9e5b-c691cc972a39.jpg)
Can you uploading the *.sln project file and uploading the asi flie already build?????

I want to just coding in Lua If you uploading the asi flie ,
I don't like open vs2013 to build the C++ file.......It make me painful..

I‘m in China.Easy visit github,but not easy to visit foreign web ....

**Comment by Freeeaky** [comment]
There is actually no need to download it from my website.
You can also download it here directly from Github: https://github.com/Freeeaky/GTALua/releases/tag/1.1.0

You were fast, dethboykill ^^

**Comment by jacobgc** [comment]
I get emails for every issue :P

**Comment by Freeeaky** [comment]
Haha, just like me :D
You should join IRC some time, btw

I really appreciate you helping with this!

**Comment by jacobgc** [comment]
I have no idea how to join an IRC, halp :P

**Comment by Freeeaky** [comment]
Download an IRC client (like HexChat), join irc.gtanet.com (Port 6667) and join #gtalua :D
You can send me an email if you want to discuss further :+1:

**Comment by wijat** [comment]
I download this:

https://github.com/Freeeaky/GTALua/releases/download/1.1.0/GTALua_1.1.0.zip

It not necessarily succeed connect..

Thank you for help,
I download it finish.

It is midnight in here.Goodbye.
