### ISSUE TITLE
gui.NotifyAboveMap

### ISSUE THREAD

**Issue by Freeeaky** [Freeeaky/GTALua#45]
The seatbelt mod reported that gui.NotifyAboveMap is not working correctly, at least the time parameter isn't.

**Comment by kanersps** [comment]
1000 = 4-5 seconds.

**Comment by Freeeaky** [comment]
Could the second parameter be frames/ticks ?
Am 19.05.2015 20:39 schrieb "kanersps" notifications@github.com:

**Comment by kanersps** [comment]
Yes it is! I just tried with self:Wait(1) and that will make it work propely
I had it to 5 before, so thats the issue.

**Comment by Freeeaky** [comment]
Turns out that the parameter isn't time, but instead "blink".
