### ISSUE TITLE
Add console commands to documentation

### ISSUE THREAD

**Issue by Freeeaky** [Freeeaky/GTALua#5]
People have trouble finding out how to reload their script

**Comment by ghost** [comment]
I've reloaded from console with "reload_addon [name_addon]" but it worked only one time.
Is it possible?

**Comment by Freeeaky** [comment]
It's something that I'm looking into, it might be abug.
Thanks for the report.

2015-04-29 2:11 GMT+02:00 hackLover notifications@github.com:
