### ISSUE TITLE
Suggestion for fixing SET_VEHICLE_NUMBER_PLATE_TEXT_INDEX

### ISSUE THREAD

**Issue by Offline-R503B** [Freeeaky/GTALua#52]
In native_call_layout.ini
SET_VEHICLE_NUMBER_PLATE_TEXT_INDEX=as)v  Doesn't work
z00t and I tested around a bit and it seems that: 
SET_VEHICLE_NUMBER_PLATE_TEXT_INDEX=aa)v Works

natives.VEHICLE.SET_VEHICLE_NUMBER_PLATE_TEXT_INDEX(Vehicle vehicle, string)
Becomes
natives.VEHICLE.SET_VEHICLE_NUMBER_PLATE_TEXT_INDEX(Vehicle vehicle, int)

**Comment by z00t** [comment]
VEHICLE::SET_VEHICLE_NUMBER_PLATE_TEXT_INDEX
Hashes: 0x9088EB5A43FFB0A1 0xA1A1890E

void SET_VEHICLE_NUMBER_PLATE_TEXT_INDEX(Vehicle vehicle, int PlateIndex)
// 0x9088EB5A43FFB0A1 0xA1A1890E

from NativeDB

**Comment by Freeeaky** [comment]
Ah thank you, i'll fix this later today.
