### ISSUE TITLE
Suggestion for fixing VEHICLE.SET_VEHICLE_NEON_LIGHT_ON

### ISSUE THREAD

**Issue by Offline-R503B** [Freeeaky/GTALua#54]
Just tested my neon after changing to latest version and they didn't work.
z00t and I out this was the reason: 
You added SET_VEHICLE_NEON_LIGHT_ON
Which should be SET_VEHICLE_NEON_LIGHT_ENABLED
In both the INI files

**Comment by jacobgc** [comment]
He's right you know. _Insert meme here_

**Comment by Freeeaky** [comment]
Just fixed that, thanks for the report :)
SET_VEHICLE_NEON_LIGHT_ON is still there so I don't break anything :D

https://github.com/Freeeaky/GTALua/commit/45f119451b34a2408c4da333f7ab22120b611651
