### ISSUE TITLE
Issue with .RPFs?

### ISSUE THREAD

**Issue by kmcgurty** [Freeeaky/GTALua#56]
Someone was trying to install my menu and GTALua crashed with this error:
http://puu.sh/iaSxd/de39ff0a60.png
I have no clue if it's an end user problem, or a problem with GTALua, so I'm submitting an issue about it

**Comment by Freeeaky** [comment]
I think that he's using FiveM, because those trace messages are definetly not from me.

**Comment by kmcgurty** [comment]
He said he wasn't using FiveM, but mentioned that it could possibly be a problem with his hdd. I still have no clue

**Comment by Freeeaky** [comment]
Those error/warning messages are definetly not from GTALua. Ask him to provide a full list of addons.
