### ISSUE TITLE
Natives who need a string argument causes an error

### ISSUE THREAD

**Issue by vincentducorps** [Freeeaky/GTALua#60]
Hi,

Whenever I try to use a native that contains a string argument, there is an error!
###### Example :

``` lua
natives.VEHICLE.SET_VEHICLE_NUMBER_PLATE_TEXT(vehicle_id, text)
```

Return an error : "Argument type mismatch (index 2 - got string expected a number)"

This seems to be due to an error in the file native_call_layout.ini
Why there is no more string type like in 1.0.1 but unknow element?

``` txt
SET_VEHICLE_NUMBER_PLATE_TEXT=iu)v
```

Thanks

**Comment by vincentducorps** [comment]
Indeed, if I change **u** by **s**, it works!

I use the latest version of files (modified there 5 days), so it's necessary that you regenerated with the inclusion of string type :)

**Comment by kmcgurty** [comment]
Just to let you know, you add this somewhere in your script so you don't have to edit the natives.ini <code>natives.VEHICLE.SET_VEHICLE_NUMBER_PLATE_TEXT:AddCallLayout("is)v")</code>

**Comment by vincentducorps** [comment]
Thank you for the tip @kmcgurty !

**Comment by Freeeaky** [comment]
Oh, I just noticed. I'll have to fix the ini generation I guess. I'll do that tomorrow - I suggest you use the version before that then. Sorry for that.

**Comment by vincentducorps** [comment]
Perfect!

**Comment by Freeeaky** [comment]
Fixed, https://github.com/Freeeaky/GTALua/commit/4f1d69265934f64b1c147f6b81bdc5b6bbd2e0e9
