### ISSUE TITLE
Unknown category SOCIALCLUB

### ISSUE THREAD

**Issue by Freeeaky** [Freeeaky/GTALua#67]
http://puu.sh/isn3K/a8ad68db71.PNG

**Comment by vincentducorps** [comment]
This need Script Hook SDK update ! Not released for now !

**Comment by Freeeaky** [comment]
Huh, why ScriptHook SDK ?
The error is caused by GTALua

**Comment by vincentducorps** [comment]
Natives aren't defined here? => https://github.com/Freeeaky/GTALua/blob/master/src/GTALua/thirdparty/ScriptHookV/inc/natives.h

**Comment by vincentducorps** [comment]
Sorry, like I said, I'm not a C developper ! lol

**Comment by Freeeaky** [comment]
Nope, this file isn't used at all.
The natives are defined in the inis :)
