### ISSUE TITLE
Auto-updater 

### ISSUE THREAD

**Issue by vincentducorps** [Freeeaky/GTALua#69]
What do you think about auto-updater and  release more frequently ?

I found this library, looks interesting : http://winsparkle.org/

I'm not a C/C++ developper, I know nothing Jan Snow !

**Comment by Freeeaky** [comment]
I like the idea of an auto-updater, but I'm not sure everyone will.
Ever since that Angry Planes / Noclip thing, people are very careful (I don't blame them) - I'm not sure they would like that.

**Comment by vincentducorps** [comment]
In this case, I suggest you leave the choice to the user in the gtalua.ini file :)

Also with this library you can allow skipping when a new update is available !

**Comment by Freeeaky** [comment]
If I decide to add an auto-updater, I'll probabbly not use a library :)

**Comment by vincentducorps** [comment]
I trust you ;)

**Comment by Freeeaky** [comment]
After some thinking I decided to not add an auto-updater.
People are distrustful as-is with the malware found & I believe an updater makes it worse.
Furthermore, some forums don't allow network connectivity so that's another contra argument.
