### ISSUE TITLE
Add a command to restart GTALua without restarting the game

### ISSUE THREAD

**Issue by vincentducorps** [Freeeaky/GTALua#71]
Hi,

Can you add a command to restart GTALua without restarting the game ?

It could be good especially for Lua Panic crash

((And also for GTALua developers ;) ))

**Comment by Freeeaky** [comment]
Hey,

you shouldn't be experiencing Lua Panics.. That shouldn't happen, at all..

**Comment by vincentducorps** [comment]
lol

That's when I push too many times F9 key ;)

**Comment by vincentducorps** [comment]
Can be linked with #59

**Comment by Freeeaky** [comment]
So what exactly happens then?
Any messages?

**Comment by Freeeaky** [comment]
Please add some more information, otherwise I'll close this.
