### ISSUE TITLE
Player:GetAimedEntity() cannot return object

### ISSUE THREAD

**Issue by seifer7** [Freeeaky/GTALua#78]
Due to a small typo in this function, an object can't be returned.

Player.lua file

```
96: if ent:IsPed() then
97:     return Ped(ent_id)
98: elseif ent:IsVehicle() then
99:     return Vehicle(ent_id)
100: elseif ent:IsObject() then
101:     return Object(ent)
102: end
```

Line 101 should be
`return Object(ent_id)`

**Comment by Freeeaky** [comment]
This is already fixed in the new Version, thanks for the report tho ;)
Am 01.08.2015 15:59 schrieb "loveletslive7" notifications@github.com:

**Comment by seifer7** [comment]
Np. I'll post if I come across anything else. I already noticed a bunch of things were fixed but I was using an old version _rolls eyes_
