### ISSUE TITLE
Can the script run in the online mode by using GTALua?

### ISSUE THREAD

**Issue by jjmon** [Freeeaky/GTALua#79]
As we know, the script example "NativeTrainer.asi"  provided by Alexander Blade (the author of Script Hook V)  can not run in the online mode. I'd like to if I use the GTALua engine; then can the script run in the online mode? Or how can I get the script  to work in the online mode? I don't know the method. Can you share some?

**Comment by Freeeaky** [comment]
If you use the bypass, you can use GTALua online ;)
Am 04.08.2015 18:14 schrieb "jjmon" notifications@github.com:

**Comment by JannyMon** [comment]
If  I write the script in other language, such as .net, python,or C++, which method can I use? I need some  more specific methods?

**Comment by jacobgc** [comment]
You can use a scripthook.dll that has been modified to work online. Google; online script hook.dll online
