### ISSUE TITLE
Add empty script to get people started

### ISSUE THREAD

**Issue by Freeeaky** [Freeeaky/GTALua#8]
People who just started learning Lua might find it hard to get started

**Comment by jacobgc** [comment]
What are these weird "issues" that you are making?

**Comment by Freeeaky** [comment]
They are notes to myself :)
This is kind of my To-Do list :D It's not exactly an issue.

**Comment by jacobgc** [comment]
Oh ok, while your here. I'm trying to make my first mod in lua but when its loading the script I get the error: main.lua:3: attempt to index global 'sinhax' (a nil value)

Here is my code: 

example_addon = ScriptThread("sinhax")

function sinhax:Run()
    while self:IsRunning() do
    end
    return 1
end

-- OnError
function example_vehicle:OnError()
    -- If :Run causes an error, this function is called
    -- You have 3 options here
    -- -> 1: Reset
    --       The :Run function is ran again
    -- -> 2: Kill
    --       This will Kill the thread ->completely<-
    --       After that you'll not be able to restart the thread
    -- -> 3: Do Nothing
    --       The thread will be kept alive
    --       You are able to restart the thread with reload_addon
    --
    -- I recommend that you keep the thread alive (option 1/3)
    -- because if you Kill it, you can no longer work with it!
    print("Oh no! sinhax fucked up!")
    self:Reset()
end

sinhax:Register()

Thanks for any help, if you give me any <3 :+1:

**Comment by Freeeaky** [comment]
example_addon = ScriptThread("sinhax")

Replace example_addon with sinhax :)

**Comment by jacobgc** [comment]
oh god, im so blind! Thanks for the help <3

**Comment by Freeeaky** [comment]
Sure, but as a reminder: Thre are lots of places to ask for help - It's not supposed to be here :)

**Comment by jacobgc** [comment]
You were here, thats why I asked :P

**Comment by Freeeaky** [comment]
I'm also on IRC, actively looking through my emails (that's why I responded so quickly), checking GTAForums, unknowncheats and mpgh every few minutes :)

**Comment by dethboykill** [comment]
Nice!

**Comment by Freeeaky** [comment]
https://github.com/Freeeaky/GTALua/commit/2e087bb796dab4ef5f708325a65f91221e199089
