### ISSUE TITLE
About  the menu language

### ISSUE THREAD

**Issue by jjmon** [Freeeaky/GTALua#80]
If  I want to draw the menu in different language , such as English, German or Chinese , what should I do? Because in the example ,all the menu language is English , I don't know the way to use other language.

**Comment by Freeeaky** [comment]
You just need to change the parameters ;)
Am 08.08.2015 15:47 schrieb "jjmon" notifications@github.com:

**Comment by jjmon** [comment]
How to change ? Which function ?
