### ISSUE TITLE
How to generate the native_call_layout.ini and natives.ini files?

### ISSUE THREAD

**Issue by vincentducorps** [Freeeaky/GTALua#83]
Hi,

How do you usually do?

Thanks!

**Comment by Freeeaky** [comment]
Hey, nice to see you're interested in fixing up GTALua. Make sure to contact me if you need help :D You can also send me an E-Mail :)

I create them using a PHP script - a very messy one. I will upload new versions of the two files in just a few moments.

**Comment by Freeeaky** [comment]
Oh, might just take some time - I lost my FTP login, sorry.
I'll do it today or tomorrow.

**Comment by vincentducorps** [comment]
Hey Freeeaky,

Yes, I work on it!
I have some ideas, I'll send you a mail to talk about it.

For your PHP script, can you add it in a branch of the project?

**Comment by Freeeaky** [comment]
Yep, will do that in a moment!

**Comment by Freeeaky** [comment]
Hey, please send me an E-Mail from your account and I will send over the PHP script there.
It's not very performant and so I don't want to upload it publicly, hope you understand.
