### ISSUE TITLE
Wiki down

### ISSUE THREAD

**Issue by bilenkonito** [Freeeaky/GTALua#97]
The wiki seems to be down, which makes development a bit complicated sometimes.
It is currently throwing this error: [http://puu.sh/nst9x/302b5ca42c.png](http://puu.sh/nst9x/302b5ca42c.png)

**Comment by Freeeaky** [comment]
Hello, sorry for the trouble! Thank you for reporting this here.
I am working on this, will update here later.

In the meantime feel free to ask any questions you have here or send me an E-Mail. Sorry for the trouble!

**Comment by Freeeaky** [comment]
The Wiki is up again! Thanks again for reporting the problem.
I'll close this, if you still have any questions just send me an E-Mail.
